package main

import (
	"fmt"
	"io"
	"net/http"
)

//type Autogenerated []struct {
//	CommonName string `json:"common_name"`
//}

func GetJsonFromCrt(domain string) {

	resp, err := http.Get(fmt.Sprintf("https://crt.sh/?q=%s&output=json", domain))
	if err != nil {
		fmt.Println(err)
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	fmt.Println(string(body))
}

func main() {
	GetJsonFromCrt("facebook.com")
}
